import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';

class FaqScreen extends StatelessWidget {
  const FaqScreen({super.key});

  static const _items = [
    (
      q: 'What is TradeGenZ?',
      a:
          'TradeGenZ is a platform that provides real-time forex trading signals generated by professional analysts and AI-assisted tools.',
    ),
    (
      q: 'How do I read a signal?',
      a:
          'Each signal shows the currency pair, direction (BUY/SELL), entry price, stop loss (SL), and take profit (TP). Enter the trade at the entry price, set your SL and TP accordingly.',
    ),
    (
      q: 'What is the difference between Free and Premium?',
      a:
          'Free users get limited signals with a delay. Premium users get real-time high-frequency signals, push notifications, and access to all premium features.',
    ),
    (
      q: 'How do I upgrade to Premium?',
      a:
          'Go to your Profile and tap "Upgrade". You can subscribe monthly or yearly via in-app purchase.',
    ),
    (
      q: 'What does TP HIT / SL HIT mean?',
      a:
          'TP HIT means the take profit target was reached — a winning trade. SL HIT means the stop loss was triggered — the trade closed at a loss.',
    ),
    (
      q: 'How is Win Rate calculated?',
      a:
          'Win Rate is the percentage of closed signals that hit the take profit target. It is calculated from all your completed signals.',
    ),
    (
      q: 'I have a problem with my subscription. Who do I contact?',
      a:
          'Please email us at chloeder29@gmail.com and we will assist you as soon as possible.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.help_outline, size: 20),
            const SizedBox(width: 8),
            const Text('Help & FAQ'),
          ],
        ),
      ),
      body: ListView.separated(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        itemCount: _items.length,
        separatorBuilder: (_, _) => const SizedBox(height: 8),
        itemBuilder: (context, index) {
          final item = _items[index];
          return _FaqTile(question: item.q, answer: item.a);
        },
      ),
    );
  }
}

class _FaqTile extends StatelessWidget {
  final String question;
  final String answer;
  const _FaqTile({required this.question, required this.answer});

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: ExpansionTile(
        backgroundColor: AppColors.surfaceContainer,
        collapsedBackgroundColor: AppColors.surfaceContainerLow,
        iconColor: AppColors.primary,
        collapsedIconColor: AppColors.onSurfaceVariant,
        tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        title: Text(
          question,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.onSurface,
          ),
        ),
        children: [
          Text(answer, style: AppTextStyles.body),
        ],
      ),
    );
  }
}
